[nodejs]
disabled = true

[docker_context]
disabled = false

[git_branch]
symbol = "ğŸŒ¿ "

[python]
symbol = "ğŸ "

[directory]
truncation_length = 3
truncate_to_repo = true

[character]
vicmd_symbol = "[V](bold green)"
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

[memory_usage]
disabled = false
threshold = -1
symbol = "ğŸ§  "
style = "bold dimmed green"

[time]
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"

[custom.vi_mode]
command = "echo $STARSHIP_SHELL_KEYMAP"
when = "test -n \"$STARSHIP_SHELL_KEYMAP\""
format = "[$output]($style) "
style = "bold blue"
